exec-once = wl-clipboard-history -t
exec-once = sunshine
exec-once = ~/.config/hypr/xdg-portal-hyprland.sh
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
exec-once = eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
exec-once = export SSH_AUTH_SOCK
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = wlsunset -S 9:00 -s 19:30
exec-once = dunst
exec-once = waybar
exec-once = swww-daemon
exec-once = waypaper --restore
exec-once = copyq
exec-once = hyprlock
exec-once = wayvnc 0.0.0.0 5900
exec-once = hypridle
exec-once = steam -silent
exec-once = openrgb -c 000000
exec-once = hyprpm reload
exec-once = nm-applet
exec-once = blueman-applet
exec-once = ferdium
exec-once = signal-desktop --start-in-tray
exec-once = bitwarden-desktop
