exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP HYPRLAND_INSTANCE_SIGNATURE SSH_AUTH_SOCK
exec-once = wl-clipboard-history -t
exec-once = systemctl --user start gnome-keyring-daemon.service
exec-once = systemctl --user start hyprland-session.target
exec-once = ~/.config/hypr/xdg-portal-hyprland
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
exec-once = wlsunset -S 9:00 -s 19:30
exec-once = awww-daemon
exec-once = waypaper --restore
exec-once = hyprlock
exec-once = wayvnc 0.0.0.0 5900
exec-once = steam -silent
exec-once = openrgb -c 000000
exec-once = hyprpm reload
exec-once = signal-desktop --start-in-tray
