general {
    lock_cmd = hyprlock    # Fallback if something calls loginctl lock-session
}

listener {
    timeout = 600           # lock after 60s (set to whatever you want)
    on-timeout = hyprlock  # directly call hyprlock
}
