dwindle {
  pseudotile = true
  preserve_split = true
  split_width_multiplier = 1.0
}

master {
  mfact = 0.55
  new_status = slave
  new_on_top = false
  new_on_active = none
  orientation = left
  smart_resizing = true
  drop_at_cursor = true
  always_keep_position = false
  allow_small_split = false
}
