hl.monitor({
  output = "DP-2",
  mode = "highrr",
  position = "0x0",
  scale = "1.0",
  bitdepth = 10,
  cm = "hdr",
  sdrbrightness = 0.5,
  sdrsaturation = 1.0,
  sdr_min_luminance = 0.0,
  sdr_max_luminance = 456,
  min_luminance = 0.0,
  max_luminance = 456,
  max_avg_luminance = 254,
  vrr = 3,
})
